name: Docker build

on: [push, pull_request]

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build
      run: make docker_build
